### ISSUE TITLE
MTU for docker-compose

### ISSUE THREAD

**Issue by lcarva** [containerbuildsystem/osbs-box#57]
If docker daemon requires a non-default MTU value (VM on OpenStack for example), docker-compose does not automatically pick up this value. Instead, it uses the default 1500.

To get around this issue docker-compose must be modified to include:
```
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1400
```
